aws_access_key: "YOUR_ACCESS_KEY"
aws_secret_key: "YOUR_SECRET_KEY"
aws_region: "ap-south-1"
s3_bucket_name: "terfbuc"
vpc_cidr_block: "10.0.0.0/16"
subnet_cidr_block: "10.0.0.0/24"
ec2_ami: "ami-0607784b46cbe5816"
ec2_instance_type: "t2.micro"
