name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

     

     aws_access_key: "YOUR_ACCESS_KEY"
     aws_secret_key: "YOUR_SECRET_KEY"
     aws_region: "ap-south-1"
     s3_bucket_name: "terfbuc"
     vpc_cidr_block: "10.0.0.0/16"
     subnet_cidr_block: "10.0.0.0/24"
     ec2_ami: "ami-0607784b46cbe5816"
     ec2_instance_type: "t2.micro"
    - run: 
        terraform_init:
        command: init

        terraform_plan:
        command: plan

        terraform_apply:
        command: apply -auto-approve


     # - name: Run Terraform commands
      #  run: |
       #   terraform init -input=false
        #  terraform plan -input=false -var-file=config.yml
         # terraform apply -input=false -auto-approve -var-file=config.yml
