name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Install AWS CLI
        run: |
          sudo apt-get update && \
          apt-get install -y curl unzip && \
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
          unzip awscliv2.zip && \
          sudo ./aws/install

      - name: Configure AWS credentials
        run: |
          echo "[default]" > aws_credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> aws_credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> aws_credentials
          echo "region=${{ secrets.AWS_REGION }}" >> aws_credentials
          export AWS_SHARED_CREDENTIALS_FILE=$(pwd)/aws_credentials

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform plan
        run: terraform plan -input=false -var-file=config.yml

      - name: Terraform apply
        run: terraform apply -input=false -auto-approve -var-file=config.yml
