name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

    #  - name: Install AWS CLI
     #   run: |
      #    apt-get update && \
       #   apt-get install -y curl unzip && \
        #  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
         # unzip awscliv2.zip && \
          #sudo ./aws/install

      - name: Configure AWS credentials
        run: |
          aws_access_key: "YOUR_ACCESS_KEY"
          aws_secret_key: "YOUR_SECRET_KEY"
          aws_region: "us-west-2"
          s3_bucket_name: "my-bucket"
          vpc_cidr_block: "10.0.0.0/16"
          subnet_cidr_block: "10.0.0.0/24"
          ec2_ami: "ami-0123456789abcdef0"
          ec2_instance_type: "t2.micro"

      - name: Run Terraform commands
        run: |
          terraform init -input=false
          terraform plan -input=false -var-file=config.yml
          terraform apply -input=false -auto-approve -var-file=config.yml
