name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Install AWS CLI
        run: |
          apt-get update && \
          apt-get install -y curl unzip && \
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
          unzip awscliv2.zip && \
          sudo ./aws/install

      - name: Configure AWS credentials
        run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}" > ~/.aws/credentials
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Run Terraform commands
        run: |
          terraform init -input=false
          terraform plan -input=false -var-file=config.yml
          terraform apply -input=false -auto-approve -var-file=config.yml
